[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "no-cache"
  X-Content-Type-Options = "nosniff"

 [build.environment]
  HTTP2 = "false"