name: Continuous delivery

on:
  push:
    branches: [main]

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: mkdir output && echo "Arquivo de exemplo" > output/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/

  deploy:
    runs-on: ubuntu-latest
    needs: deliver

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Mostrar conteúdo baixado
        run: ls -R
